# æ­¤å¼€æºé¡¹ç›®åœ°å€ https://github.com/lowlighter/metrics

name: Github_Skyline_workflow

on:
  schedule:
    - cron: "0 0 * * *"
    # https://docs.github.com/zh/actions/using-workflows/events-that-trigger-workflows#schedule
  workflow_dispatch:
  push: { branches: ["master", "main"] }
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # åŸºç¡€ä¿¡æ¯ï¼ˆé¡ºå¸¦äº†å‡ ä¸ªå°æ’ä»¶ï¼‰
      - name: base
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/base.svg
          # Your GitHub token
          token: ${{ secrets.SKYLINE_TOKEN }}
          # Options
          user: humb1e1989
          template: classic
          config_timezone: Asia/Shanghai
          base: "header, activity, community, repositories"
          # æ­¤æ’ä»¶ä¸ºæ–‡æ¡£ä¸­çš„ ðŸ§® Repositories traffic
          plugin_traffic: yes
          # æ­¤æ’ä»¶ä¸ºæ–‡æ¡£ä¸­çš„ ðŸ‘¨â€ðŸ’» Lines of code changed
          plugin_lines: yes
          # æ­¤æ’ä»¶ä¸ºæ–‡æ¡£ä¸­çš„ ðŸ™‹ Introduction
          plugin_introduction: yes
          # æ­¤æ’ä»¶ä¸ºæ–‡æ¡£ä¸­çš„ ðŸŽ« Gists
          plugin_gists: yes
          # æ­¤æ’ä»¶ä¸ºæ–‡æ¡£ä¸­çš„ ðŸ’« Star lists
          plugin_starlists: yes
          plugin_starlists_limit_repositories: 2
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8
          plugin_starlists_only: Awesome
          
      # # ðŸ“… Isometric commit calendar
      # - name: Full-year calendar
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: .github/isocalendar.fullyear.svg
      #     token: ${{ secrets.SKYLINE_TOKEN }}
      #     # ä¸æ·»åŠ åŸºç¡€ä¿¡æ¯
      #     base: ""
      #     # ä½¿ç”¨æ­¤æ’ä»¶
      #     plugin_isocalendar: yes
      #     # è®¾ç½®æˆæ˜¾ç¤ºæ•´å¹´
      #     plugin_isocalendar_duration: full-year

      # # ðŸˆ·ï¸ Languages activity
      # - name: Indepth analysis
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: .github/languages.indepth.svg
      #     token: ${{ secrets.SKYLINE_TOKEN }}
      #     base: ""
      #     plugin_languages: yes
      #     plugin_languages_ignored: >-
      #       html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
      #       gnuplot
      #     plugin_languages_indepth: yes
      #     plugin_languages_details: lines, bytes-size
      #     plugin_languages_limit: 4
      #     plugin_languages_analysis_timeout: 15

      # # âœ¨ Stargazers   
      # - name: Using chartist charts
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: .github/stargazers.chartist.svg
      #     token: ${{ secrets.SKYLINE_TOKEN }}
      #     base: ""
      #     plugin_stargazers: yes
      #     plugin_stargazers_charts_type: chartist

      # # ðŸŒŸ Recently starred repositories
      # - name: Recently starred
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: .github/stars.svg
      #     token: ${{ secrets.SKYLINE_TOKEN }}
      #     base: ""
      #     plugin_stars: yes
      #     plugin_stars_limit: 10
          
      # # ðŸ’¡ Coding habits and activity
      # - name: Recent activity charts
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: .github/habits.charts.svg
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     base: ""
      #     plugin_habits: yes
      #     plugin_habits_facts: no
      #     plugin_habits_charts: yes
      #     config_timezone: Europe/Paris
          
      # # ðŸŽŸï¸ Follow-up of issues and pull requests 
      # - name: Indepth analysis
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: .github/followup.indepth.svg
      #     token: ${{ secrets.SKYLINE_TOKEN }}
      #     base: ""
      #     plugin_followup: yes
      #     plugin_followup_indepth: yes
          
      # # ðŸŽ­ Comment reactions
      # - name: Comment reactions
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: .github/reactions.svg
      #     token: ${{ secrets.SKYLINE_TOKEN }}
      #     base: ""
      #     plugin_reactions: yes
      #     plugin_reactions_limit: 100
      #     plugin_reactions_details: percentage

      # # ðŸ§‘â€ðŸ¤â€ðŸ§‘ People    
      # - name: Followers
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: .github/people.followers.svg
      #     token: ${{ secrets.SKYLINE_TOKEN }}
      #     base: ""
      #     plugin_people: yes
      #     plugin_people_limit: 500
      #     plugin_people_size: 36
      #     plugin_people_types: followers, following
          
      # # ðŸ““ Featured repositories
      # - name: Pinned repositories
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: .github/repositories.pinned.svg
      #     token: ${{ secrets.SKYLINE_TOKEN }}
      #     base: ""
      #     plugin_repositories: yes
      #     plugin_repositories_pinned: 2

      # # ðŸ’¬ Discussions
      # - name: GitHub Discussions
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: .github/discussions.svg
      #     token: ${{ secrets.SKYLINE_TOKEN }}
      #     base: ""
      #     plugin_discussions: yes
      #     plugin_discussions_categories_limit: 8       
   
      # # ðŸ“† Commit calendar
      # - name: Full history calendar
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: .github/calendar.full.svg
      #     token: ${{ secrets.SKYLINE_TOKEN }}
      #     base: ""
      #     plugin_calendar: yes
      #     plugin_calendar_limit: 0

      # # ðŸ† Achievements
      # - name: Compact display
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: .github/achievements.compact.svg
      #     token: ${{ secrets.SKYLINE_TOKEN }}
      #     base: ""
      #     plugin_achievements: yes
      #     plugin_achievements_only: >-
      #       polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
      #       scripter, packager, explorer, infographile, manager
      #     plugin_achievements_display: compact
      #     plugin_achievements_threshold: X

      # # ðŸ“° Recent activity
      # - name: Recent activity
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: .github/activity.svg
      #     token: ${{ secrets.SKYLINE_TOKEN }}
      #     base: ""
      #     plugin_activity: yes
      #     plugin_activity_limit: 5
      #     plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
